#include "arduino_secrets.h"
// OneWire - Version: Latest 
#include <OneWire.h>

// DallasTemperature - Version: 3.8.0
#include <DallasTemperature.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "MKR-1010-TEMP"
  https://create.arduino.cc/cloud/things/2ebd2327-fd77-43ff-ad36-f441c17e328b 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float be_temp;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


#define ONE_WIRE_BUS 2
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature sensors(&oneWire);
DeviceAddress insideThermometer;

void setup() {
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 3     
 */
  setDebugMessageLevel(2);

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  Serial.println("Dallas Temperature IC Control Library Demo");
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // Start temperature readings
  be_temp = 0.0;
  
  sensors.begin();

  sensors.getAddress(insideThermometer, 0);
  sensors.setResolution(insideThermometer, 9);
}

void loop() {
  ArduinoCloud.update();
  
  // Get current temperature
  Serial.print("Requesting temperatures...");
  sensors.requestTemperatures();
  Serial.println("DONE");
  
  be_temp = sensors.getTempC(insideThermometer);
  Serial.print("Temperature for the device is: ");
  Serial.println(be_temp);
}







































